CREATE DATABASE Desktop_BetaBD;
USE Desktop_BetaBD;

CREATE TABLE IF NOT EXISTS cliente (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
cpf CHAR(14) NOT NULL,
data_nascimento DATE NOT NULL,
email VARCHAR(100) NOT NULL,
senha_hash CHAR(64) NOT NULL,
senha_salt CHAR(32) NOT NULL,
ativo TINYINT(1) NOT NULL DEFAULT 1
)