CREATE DATABASE Desktop_BetaBD;
USE Desktop_BetaBD;

CREATE TABLE usuario (
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS cliente (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
cpf CHAR(14) NOT NULL,
data_nascimento DATE NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(30) NOT NULL
)